/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java Library project to get you started.
 * For more details take a look at the Java Libraries chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.2.2/userguide/java_library_plugin.html
 */

plugins {
    `java-library`
}

group = "com.therolf"
version = "0.1"

repositories {
    jcenter()
}

dependencies {

    implementation("org.swinglabs.swingx:swingx-all:1.6.4")

    //implementation("io.github.vincenzopalazzo:material-ui-swing:1.1.1_pre-release_6.1")
    implementation(files("$projectDir/libs/material-ui-swing-1.1.1_0.2.jar"))
}
